import os
import re
import json
import argparse
import requests
from groq import Groq


MAX_SOURCES = 4
MAX_CONTENT_CHARS = 500
MAX_REPORT_CHARS = 5000


def get_required_env(name):
    value = os.getenv(name)
    if not value:
        raise ValueError(
            f"Missing environment variable: {name}\n"
            f'Set it in PowerShell like this:\n'
            f'$env:{name}="YOUR_KEY_HERE"'
        )
    return value


def shorten(text, max_chars):
    if not text:
        return ""
    text = " ".join(str(text).split())
    return text[:max_chars]


def read_text_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def extract_json_from_text(text):
    """
    Extract JSON object from LLM output.
    """
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError("No JSON object found in extraction output.")
    return json.loads(match.group(0))


def extract_spill_data_from_llm_report(report_text):
    """
    Uses Groq to extract structured spill data from the first LLM report.
    This does NOT use database.
    """
    groq_key = get_required_env("GROQ_API_KEY")
    groq_client = Groq(api_key=groq_key)

    report_text = shorten(report_text, MAX_REPORT_CHARS)

    prompt = f"""
You will receive an oil spill analysis report generated by another LLM/model.

Your task:
Extract the important fields needed for oil spill response search.

Rules:
- Do not invent values.
- If a value is missing, use "unknown".
- Return ONLY valid JSON.
- The report may be Arabic or English.
- Keep units if available.

Required JSON fields:
{{
  "spill_id": "",
  "risk_level": "",
  "area": "",
  "latitude": "",
  "longitude": "",
  "distance_to_shoreline": "",
  "distance_to_coral": "",
  "wind_speed": "",
  "wind_direction": "",
  "sea_conditions": "",
  "environmental_sensitivity": "",
  "analysis_summary": ""
}}

LLM Report:
{report_text}
"""

    response = groq_client.chat.completions.create(
        model=os.getenv("GROQ_MODEL", "llama-3.1-8b-instant"),
        messages=[
            {
                "role": "system",
                "content": "You extract structured JSON from oil spill reports. Return only JSON."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.1,
        max_tokens=700
    )

    extracted_text = response.choices[0].message.content
    return extract_json_from_text(extracted_text)


def search_web(query, max_results=2):
    tavily_key = get_required_env("TAVILY_API_KEY")

    payload = {
        "api_key": tavily_key,
        "query": query,
        "search_depth": "basic",
        "include_answer": False,
        "include_raw_content": False,
        "max_results": max_results
    }

    response = requests.post(
        "https://api.tavily.com/search",
        json=payload,
        timeout=30
    )
    response.raise_for_status()

    data = response.json()

    results = []
    for item in data.get("results", []):
        results.append({
            "title": shorten(item.get("title", ""), 150),
            "url": item.get("url", ""),
            "content": shorten(item.get("content", ""), MAX_CONTENT_CHARS),
            "query": query
        })

    return results


def build_search_queries(spill_data):
    risk_level = spill_data.get("risk_level", "unknown")
    area = spill_data.get("area", "unknown")
    distance_to_coral = spill_data.get("distance_to_coral", "unknown")
    distance_to_shoreline = spill_data.get("distance_to_shoreline", "unknown")
    wind_direction = spill_data.get("wind_direction", "unknown")
    sea_conditions = spill_data.get("sea_conditions", "unknown")
    environmental_sensitivity = spill_data.get("environmental_sensitivity", "unknown")

    return [
        f"oil spill cleanup case study {risk_level} risk area {area} shoreline {distance_to_shoreline}",
        f"oil spill response near coral reefs booms skimmers dispersants coral distance {distance_to_coral}",
        f"marine oil spill response wind direction {wind_direction} sea conditions {sea_conditions}",
        f"oil spill response sensitive marine habitat {environmental_sensitivity} booms skimmers dispersants"
    ]


def collect_search_evidence(spill_data):
    all_results = []
    seen_urls = set()

    for query in build_search_queries(spill_data):
        try:
            results = search_web(query, max_results=2)

            for result in results:
                url = result.get("url", "")
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    all_results.append(result)

                if len(all_results) >= MAX_SOURCES:
                    return all_results

        except Exception as e:
            print(f"[Search Error] Query failed: {query}")
            print(e)

    return all_results


def generate_response_plan_from_report(report_text):
    """
    Main function:
    1. Reads first LLM report text.
    2. Extracts structured spill data from it.
    3. Searches the web based on extracted data.
    4. Generates cleanup response plan.
    """
    groq_key = get_required_env("GROQ_API_KEY")
    groq_client = Groq(api_key=groq_key)

    spill_data = extract_spill_data_from_llm_report(report_text)
    search_results = collect_search_evidence(spill_data)

    if not search_results:
        return "لم يتم العثور على نتائج بحث. تأكد من مفتاح Tavily أو الاتصال بالإنترنت."

    sources_text = ""
    for i, source in enumerate(search_results, start=1):
        sources_text += f"""
Source {i}
Title: {source.get("title", "")}
URL: {source.get("url", "")}
Content: {source.get("content", "")}
"""

    prompt = f"""
You are an oil spill response advisor.

You must generate the cleanup response based on:
1. The extracted spill data from the first LLM report.
2. The web search results.

Do not use database.

Language quality rules:
- Write the final answer in clean professional Arabic.
- Do not use Korean, Chinese, or random foreign words.
- Keep important English technical terms beside Arabic terms:
  Booms = الحواجز العائمة
  Skimmers = كاشطات النفط
  Dispersants = المشتتات الكيميائية
  Coral reefs = الشعاب المرجانية
  Shoreline = الساحل
- Do not mix English words randomly inside Arabic sentences.
- Use "نشر الحواجز العائمة" not "deployment الحواجز العائمة".
- Do not recommend Dispersants directly near Coral reefs.
- If Coral reefs or sensitive marine habitats are nearby, say Dispersants require environmental authority approval.
- Prefer mechanical recovery methods first: Booms and Skimmers.
- Treat Wikipedia as weak background evidence, not the main evidence.
- Make the cleanup plan practical, step-by-step, and specific.

Extracted Spill Data:
{json.dumps(spill_data, ensure_ascii=False, indent=2)}

Web Search Results:
{sources_text}

Return:
1. البيانات المستخرجة من تقرير LLM الأول
2. ملخص حالة التسرب
3. مصادر مشابهة
4. كيف تم التعامل مع حالات مشابهة
5. خطة تنظيف مقترحة
6. لماذا الخطة مناسبة
7. أفكار ابتكارية إضافية
8. المخاطر والقيود
9. روابط المصادر
"""

    response = groq_client.chat.completions.create(
        model=os.getenv("GROQ_MODEL", "llama-3.1-8b-instant"),
        messages=[
            {
                "role": "system",
                "content": "You are a careful oil spill response advisor. Be concise and evidence-based."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.3,
        max_tokens=1200
    )

    return response.choices[0].message.content


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        required=True,
        help="Path to the first LLM oil spill analysis report text file"
    )
    parser.add_argument(
        "--output",
        required=False,
        help="Optional path to save the response recommendation report"
    )

    args = parser.parse_args()

    report_text = read_text_file(args.report)
    final_report = generate_response_plan_from_report(report_text)

    print(final_report)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(final_report)
